name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Copy files via SCP
      run: |
        scp -o StrictHostKeyChecking=no -r . ec2-user@${{ secrets.HOST }}:/home/ec2-user/app

    - name: Deploy Stack
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.HOST }} << 'EOF'
          cd /home/ec2-user/app
          docker stack deploy -c docker-compose.yml ${{ secrets.STACK_NAME }}
        EOF